# Generated by Django 4.1 on 2022-08-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='country ')),
                ('address_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='address_detail')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=10)),
                ('doctor', models.CharField(blank=True, choices=[('leather', 'leather'), ('teeth', 'teeth'), ('psychiatrist', 'psychiatrist'), ('newborn children', 'newborn children'), ('brain and nerves', 'brain and nerve'), ('bones', 'bones'), ('Obstetrician and gynecologist', 'Obstetrician and gynecologist'), ('ear, nose and throat', 'ear, nose and throat'), ('Heart and blood vessels', 'Heart and blood vessels'), ('blood diseases', 'blood diseases'), ('oncologist', 'oncologist'), ('inner', 'internal'), ('Slimming and Nutrition', 'Slimming and Nutrition'), ('pediatric surgery', 'pediatric surgery'), ('Oncology', 'Oncology'), ('plastic surgery', 'cosmetic surgery')], max_length=100, null=True, verbose_name='doctor؟')),
                ('specialist_doctor', models.CharField(blank=True, max_length=100, null=True, verbose_name='  specialist_doctor')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name=' price')),
                ('hour_of_work', models.IntegerField(blank=True, null=True, verbose_name='hour_of_work')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name=' mobile')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('google', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name=' image')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
