# Generated by Django 4.1 on 2022-08-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_hour_of_work_doctor_from_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='from_of_work',
            field=models.IntegerField(blank=True, null=True, verbose_name='from_of_work'),
        ),
    ]
