# Generated by Django 4.1 on 2022-08-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_doctor_from_of_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
