# Generated by Django 3.2.15 on 2022-08-23 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_alter_doctor_day1_of_work_alter_doctor_day2_of_work_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='is_active')),
                ('num_verify', models.IntegerField(blank=True, null=True, verbose_name='num_verify')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('user_active', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
