# Generated by Django 3.2.15 on 2022-08-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isactive',
            name='expire_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
