# Generated by Django 3.2.15 on 2022-08-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_isactive_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isactive',
            name='expire_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
