# Generated by Django 4.1 on 2022-08-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_isactive_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='avg',
            field=models.CharField(blank=True, default='no hava rate yet', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.CharField(blank=True, choices=[('leather', 'leather'), ('teeth', 'teeth'), ('psychiatrist', 'psychiatrist'), ('newborn children', 'newborn children'), ('brain and nerves', 'brain and nerve'), ('bones', 'bones'), ('Obstetrician and gynecologist', 'Obstetrician and gynecologist'), ('ear, nose and throat', 'ear, nose and throat'), ('Heart and blood vessels', 'Heart and blood vessels'), ('blood diseases', 'blood diseases'), ('oncologist', 'oncologist'), ('inner', 'internal'), ('Slimming and Nutrition', 'Slimming and Nutrition'), ('pediatric surgery', 'pediatric surgery'), ('Oncology', 'Oncology'), ('plastic surgery', 'cosmetic surgery')], max_length=100, null=True, verbose_name='doctor'),
        ),
    ]
