# Generated by Django 4.1 on 2022-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
