# Generated by Django 4.1 on 2022-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_rate_owner_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='owner',
        ),
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
