# Generated by Django 3.2.15 on 2022-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default='E:/GP/media/profile/l.jpg', null=True, upload_to='patient'),
        ),
    ]
