# Generated by Django 4.1 on 2022-08-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='patient',
            name='num_verify',
            field=models.IntegerField(blank=True, null=True, verbose_name='num_verify'),
        ),
    ]
