# Generated by Django 4.1 on 2022-08-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_is_active_patient_num_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='num_verify',
        ),
    ]
